apiVersion: v1
kind: Namespace
metadata:
  name: podinfo-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
  namespace: podinfo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: podinfo
  template:
    metadata:
      labels:
        app: podinfo
    spec:
      containers:
        - name: podinfo
          image: ghcr.io/stefanprodan/podinfo:5.0.0
          ports:
            - name: http         # <--- penting, beri nama portnya
              containerPort: 9898
---
apiVersion: v1
kind: Service
metadata:
  name: podinfo
  namespace: podinfo-app
spec:
  selector:
    app: podinfo
  ports:
    - name: http               # <--- pakai nama yang sama
      protocol: TCP
      port: 80
      targetPort: 9898
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: podinfo
  namespace: podinfo-app
spec:
  host: podinfo.studentdumbways.my.id
  to:
    kind: Service
    name: podinfo
  port:
    targetPort: http           # <--- GANTI ke nama port, bukan angka
  tls:
    termination: edge
